### ISSUE TITLE
Update to SDK v2.2.2

### ISSUE THREAD

**Issue by dudematthew** [M1kep/R5ReloadedInstaller#2]
R5 Reloaded SDK already changed to v2.2.2 while installer is still at v2.2.1

Maybe reroute downloader to /latest? 
https://github.com/Mauler125/r5sdk/releases/latest

Tested with r5util version 0.14.0

**Comment by M1kep** [comment]
Hm, that's odd. It may have had the version cached if you'd ran the installer recently. Is it still only seeing v2.2.1?

**Comment by M1kep** [comment]
Going to close this out as I'm assuming it was related to a pre-release. If you run into this again feel free to re-open or create a new issue.
